=== Alejandro2307GG/EjerciciosLMSGI/ExamenDTD/menuRestaurante.dtd
<!ELEMENT local (platos, horario, recoger)>
<!ELEMENT platos (#PCDATA | plato)*>
<!ELEMENT plato (nombre+, precio?, (grande | pequeño))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT grande EMPTY>
<!ELEMENT pequeño EMPTY>
<!ELEMENT horario EMPTY>
<!ELEMENT recoger EMPTY>
<!ATTLIST local nombre CDATA #REQUIRED
                direccion CDATA #IMPLIED
                numeroTelefono CDATA #FIXED "957629087"
                losmejoresplatos IDREFS #IMPLIED>
<!ATTLIST plato nombre (pizza| macarrones| espaguetis) "pizza"
                codigo ID #REQUIRED
                codigobuenamezcla IDREF #IMPLIED>
<!ENTITY extra "Tiene extra de queso">
<!ENTITY % atributoNombre "n CDATA #REQUIRED">
<!ATTLIST horario %atributoNombre;>
<!ATTLIST recoger %atributoNombre;>

=== Alejandro2307GG/EjerciciosLMSGI/Examen/menuRestaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE local SYSTEM "menuRestaurante.dtd">
<local nombre="La mafia italiana" direccion="C/Santa Lucía nº6" numeroTelefono="957629087" losmejoresplatos="P M S">
  <platos> Son los mejores platos de esta ciudad 
  <plato nombre="pizza" codigo="P" codigobuenamezcla="M">
    <nombre> pizza 4 quesos &extra;</nombre>
    <precio>12€</precio>
   <grande/>
</plato>
  <plato nombre="macarrones" codigo="M" codigobuenamezcla="P">
   <nombre>pasta</nombre>
    <precio>9€</precio>
   <pequeño />
  </plato>
  <plato nombre="espaguetis" codigo="S">
    <nombre>pasta &extra;</nombre>
    <precio>20€</precio>
    <grande />
  </plato>
  </platos>
  <horario n="si se puede recoger en el restaurante"/>
  <recoger n="si se puede recoger en el restaurante"></recoger>
</local>
