=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/Batman.dtd
<!ELEMENT pelicula (batman, batalla, pelea)>
<!ELEMENT batman (#PCDATA | personaje)*>
<!ELEMENT personaje (ciudad, ayudante?, (heroe | villano))>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT ayudante (#PCDATA)>
<!ELEMENT heroe EMPTY>
<!ELEMENT villano EMPTY>
<!ELEMENT batalla EMPTY>
<!ELEMENT pelea EMPTY>
<!ATTLIST personaje nombre (batman | joker | superman) "batman" 
                    traje CDATA #REQUIRED
                    padres CDATA #IMPLIED
                    casado CDATA #FIXED "si"
                    codigo ID #REQUIRED
                    codigoderefe IDREF #IMPLIED>
<!ENTITY Wayne " Bruce Wayne">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST batalla %atributoNombre;>
<!ATTLIST pelea %atributoNombre;>

=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/Batman.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula SYSTEM "Batman.dtd"> 
<pelicula> 
    <batman> esta es mi pelicula favorita 
        <personaje nombre="batman" traje="negro" padres="no" codigo="b" codigoderefe="s"> 
            <ciudad>Gotham de &Wayne;</ciudad>
            <ayudante>Alfred</ayudante>
            <heroe/>
        </personaje>
        <personaje nombre="superman" traje="azul y rojo" codigo="s"> 


            <ciudad>metropolis</ciudad>
            <heroe/>
        </personaje>
    </batman>
    <batalla nombre="batalla atomica" />
    <pelea nombre="contra superman" />


</pelicula>
