=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/rios.dtd
<!ELEMENT rios (#PCDATA | largo | corto |rio)*>
<!ELEMENT rio (provincia)+>
<!ELEMENT provincia (ciudadprincipal, afluentes?, (principal | afluente))+> 
<!ELEMENT afluentes (#PCDATA)>
<!ELEMENT principal EMPTY>
<!ELEMENT afluente EMPTY>
<!ELEMENT ciudadprincipal (#PCDATA)> 
<!ELEMENT nacimiento EMPTY>
<!ELEMENT largo EMPTY>
<!ELEMENT corto EMPTY>
<!ATTLIST rio nombre (Guadalquivir | Tajo | Ebro) "Guadalquivir"
          extension CDATA #REQUIRED
          Desembocadura CDATA #IMPLIED
          lugar CDATA #FIXED "EspaÃ±a"> 
<!ATTLIST provincia codigo ID #REQUIRED>
<!ATTLIST provincia codigor IDREF #IMPLIED>
<!ATTLIST rios codigoprov IDREFS #IMPLIED>
<!ENTITY conagua "tiene mucho caudal">
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST largo %atributoNombre;>
<!ATTLIST corto %atributoNombre;>

=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/rios.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rios SYSTEM "rios.dtd">
<rios codigoprov="S E T"> 
    <rio nombre="Guadalquivir" extension="53km" lugar="España">
    <provincia codigo="S" >
        <ciudadprincipal>
           Sevilla
        </ciudadprincipal>
        <afluentes>
            Genil 
        </afluentes>
        <principal/>
    </provincia>
    </rio>
    <rio nombre="Tajo" extension="54km">
    <provincia codigo="T" >
        <ciudadprincipal>
            Madrid
        </ciudadprincipal>
        <afluentes>
            Manzanares &conagua;
        </afluentes>
        <principal/>
    </provincia>
    </rio>
    <rio nombre="Ebro" extension="54km">
        <provincia codigo="E" >
            <ciudadprincipal>
                Madrid
            </ciudadprincipal>
            <afluentes>
                Manzanares 
            </afluentes>
            <principal/>
        </provincia>
        </rio>
        <largo nombre="1" />
        <corto nombre="4" /> 
</rios>
