=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/DTD/01-dtd-videoclub.dtd
<!ELEMENT videoclub (oferta | películas)*>
<!ELEMENT películas (nombre, tipo, precio, (Disponible | Agotado))*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT Disponible EMPTY>
<!ELEMENT Agotado EMPTY>
<!ELEMENT oferta (#PCDATA | peliculareferida)*>
<!ELEMENT peliculareferida ANY>




<!ATTLIST videoclub direccion  CDATA #IMPLIED
                    nombre  CDATA #REQUIRED
                    telefono CDATA #FIXED "954738492">
<!ATTLIST películas codigo CDATA #REQUIRED
                    mc CDATA #IMPLIED>
<!ATTLIST  peliculareferida Codigo IDREF #IMPLIED
                             combinacion IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY estrellas "Mejor puntuación">

=== Alejandro2307GG/EjerciciosLMSGI/Ejercicios/DTD/01-xml-videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "01-dtd-videoclub.dtd"> 
<videoclub direccion="Calle_Andalucía_nº5" nombre="Cinesa">
    <películas codigo="AE"> 
        <nombre> Avengers Endgame</nombre>
        <tipo> Acción </tipo>
        <precio> 5€</precio>
        <Disponible/>
    </películas>
    <películas codigo="JL">  
         <nombre> Justice League </nombre>
        <tipo> Acción </tipo>
        <precio> 5€</precio>
        <Agotado/>
    </películas>
    <oferta> coste="8" 2x1
        <peliculareferida> Codigo="JL" combinacion="8"</peliculareferida>
    </oferta>
</videoclub>
